name: AEP
color: null
values:
  - key: claimId
    value: 5bacfec936fcfc18d36474c0
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: processId
    value: null
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: caseId
    value: null
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: damageId
    value: 5bacfec936fcfc18d36474bb
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: documentId
    value: 5bacfec936fcfc18d36474bc
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: foodItemId
    value: 5bacfec936fcfc18d36474bd
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: userId
    value: jsmith
    enabled: true
    description:
      content: ""
      type: text/plain
