name: DCM Investigation
color: null
values:
  - key: CaseDevServerURL
    value: investigation.deloittedcm.com
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: processId
    value: null
    enabled: true
  - key: claimId
    value: 5bae8a0e36fcfc723cf5fa35
    enabled: true
  - key: damageId
    value: 5bae8a0e36fcfc723cf5fa30
    enabled: true
  - key: documentId
    value: 5bae8a0e36fcfc723cf5fa31
    enabled: true
  - key: foodItemId
    value: 5bae8a0e36fcfc723cf5fa34
    enabled: true
  - key: userId
    value: jsmith
    enabled: true
  - key: caseId
    value: 0e64c4c6-39f0-11e9-8c62-0242ac110003
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: schedulerURL
    value: investigation.deloittedcm.com/schedule
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: |
      closedTaskId
    value: 1d9b87d2-d93b-11e8-bc01-0242ac110003
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: |
      caseExecutionID
    value: 130c1720-db86-11e8-8d9a-0242ac110003
    enabled: true
    description:
      content: ""
      type: text/plain
  - key: taskId
    value: 0e6decd9-39f0-11e9-8c62-0242ac110003
    enabled: true
