name: FedTec
color: null
values:
  - key: access_token
    value: ""
    enabled: true
  - key: refresh_token
    value: ""
    enabled: true
  - key: candidate_process_id
    value: ""
    enabled: true
  - key: task_id
    value: ""
    enabled: true
  - key: user_task_id
    value: ""
    enabled: true
  - key: processDefinitionId
    value: ""
    enabled: true
  - key: all_workflow_id
    value: ""
    enabled: true
  - key: issuer
    value: ""
    enabled: true
  - key: authorization_endpoint
    value: ""
    enabled: true
  - key: token_endpoint
    value: ""
    enabled: true
  - key: case_definition_key
    value: ""
    enabled: true
  - key: case_diagram_location
    value: ""
    enabled: true
  - key: case_instance_id
    value: ""
    enabled: true
  - key: post_id
    value: ""
    enabled: true
