name: iWorks
values:
  - key: candidate_process_id
    value: ''
  - key: processDefinitionId
    value: ''
  - key: user_task_id
    value: ''
  - key: task_id
    value: ''
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: inbox-service
    value: ''
  - key: case_definition_key
    value: ''
  - key: case_diagram_location
    value: ''
  - key: case_instance)_id
    value: fb5ae00f-55df-11f0-85d9-d28a7214cb48
  - key: case_instance_id
    value: ''
  - key: case_definition_id
    value: ''
  - key: process_plan_item_id
    value: ''
  - key: active_plan_createTime
    value: ''
  - key: OATH-client-id
    value: ''
  - key: oauth-client-secret
    value: ''
  - key: oath-client-id
    value: ''
  - key: case-user-management-server
    value: ''
  - key: user_management_service
    value: ''
color: 0
