$kind: http-request
url: "{{keycloakServer}}/realms/cllc-development/.well-known/openid-configuration"
method: GET
scripts:
  - type: afterResponse
    code: |
      pm.test("Success", function(){
          pm.response.to.have.status(200);
      }
      );

      const responseJson = pm.response.json();
      pm.environment.set('issuer', responseJson.issuer);
      pm.environment.set('authorization_endpoint', responseJson.authorization_endpoint);
      pm.environment.set('token_endpoint', responseJson.token_endpoint);
    language: text/javascript
settings: {}
order: 1000
